project:
  type: default
  output-dir: _output
  render:
    - index.qmd

metadata-files:
  - _format-common.yml

# lang i crossref (fig-prefix, tbl-prefix, sec-prefix...) venen de _format-common.yml

format:
  # html:
  #   toc: true
  #   toc-location: left
  #   number-sections: true
  #   highlight-style: a11y
  #   code-line-numbers: true
  #   code-copy: true
  #   code-overflow: wrap
  #   theme: cosmo
  pdf:
    # documentclass, classoption, papersize, fontsize, colorlinks,
    # urlcolor, linkcolor venen de _format-common.yml
    output-file: "ICE_STEAM_PFP_RogerBaigViñas_llarg.pdf"
    toc: true
    number-sections: true
    keep-tex: false
    citecolor: blue
    geometry:
      - top=1.5cm
      - bottom=1.5cm
      - left=2cm
      - right=2cm
      - includeheadfoot
      - footskip=1cm
    include-in-header:
      - portada.tex
      - text: |
          \usepackage{caption}
          \captionsetup{font=small}               % Redueix la mida de la font de les llegendes
          \captionsetup{width=0.85\textwidth}     % Limita l'amplada de les llegendes al 85% de l'amplada del text
          \usepackage{etoolbox}
          \AtBeginEnvironment{longtable}{\small}  % Redueix la mida de la font de les taules llargues
          \AtBeginEnvironment{tabular}{\small}    % Redueix la mida de la font de les taules normals
    include-before-body:
      - before-body.tex
