project:
  type: default
  output-dir: _output
  render:
    - index.qmd
 
lang: ca
 
crossref:
  fig-prefix: "Figura"
  fig-title: "Figura"
  tbl-prefix: "Taula"
  tbl-title: "Taula"
  sec-prefix: "§"
 
format:
  # html:
  #   toc: true
  #   toc-location: left
  #   number-sections: true
  #   highlight-style: a11y
  #   code-line-numbers: true
  #   code-copy: true
  #   code-overflow: wrap
  #   theme: cosmo
  pdf:
    output-file: "projecte_docent.pdf"
    toc: true
    documentclass: scrartcl
    classoption: oneside
    papersize: a4
    geometry:
      - top=1.5cm
      - bottom=2.5cm
      - left=2cm
      - right=2cm
      - includeheadfoot
      - footskip=1cm
    fontsize: 11pt
    number-sections: true
    keep-tex: false
    colorlinks: true
    urlcolor: blue
    linkcolor: blue
    citecolor: blue
    include-in-header:
      - portada.tex
      - text: |
          \usepackage{caption}
          \captionsetup{font=small}               % Redueix la mida de la font de les llegendes
          \captionsetup{width=0.85\textwidth}     % Limita l'amplada de les llegendes al 85% de l'amplada del text
          \usepackage{etoolbox}
          \AtBeginEnvironment{longtable}{\small}  % Redueix la mida de la font de les taules llargues
          \AtBeginEnvironment{tabular}{\small}    % Redueix la mida de la font de les taules normals
    include-before-body:
      - before-body.tex
